version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: 'demo'
      MYSQL_PASSWORD: 'demo'
      MYSQL_ROOT_PASSWORD: 'demo'
    volumes:
      - ./src/main/resources/db/initdb:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    expose:
      - '3306'